runtime: python39
service: fe-207
instance_class: F1

handlers:
  # ================= PERUBAHAN UTAMA DI SINI =================
  # Arahkan root URL (halaman utama) ke login.html
  - url: /
    static_files: login.html
    upload: login.html

  # Pastikan halaman login.html itu sendiri masih bisa diakses
  - url: /login.html
    static_files: login.html
    upload: login.html

  # Halaman register
  - url: /register.html
    static_files: register.html
    upload: register.html

  # Halaman utama / dashboard (setelah login)
  # Aturan ini PENTING agar window.location.href = 'index.html' tetap berfungsi
  - url: /index.html
    static_files: index.html
    upload: index.html

  # Aturan untuk file-file JavaScript di dalam folder js
  - url: /js/(.*)
    static_files: js/\1
    upload: js/(.*)

  # Backup handler jika ada file lain
  - url: /(.*)
    static_files: \1
    upload: (.*)

default_expiration: "1h"
