GET http://localhost:3000/users


###
POST http://localhost:3000/add-users
Content-Type: application/json

{
    "Title": "Judulmu",
    "Content": "Isinya "
}

###
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "Title": "Judul",
    "Content": "Isi" 
}

###
DELETE http://localhost:3000/users/2
